name: Build containers

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: touch host_key
      - run: bun run build:docker
